services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    volumes:
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8016 --reload --loop asyncio
    ports:
      - "8016:8016"
    depends_on:
      - mongodb
      - minio
      - mariadb
    networks:
      - dataviz
    environment:
      MONGO_URI: ${MONGO_URI:-"mongodb://admin:secret@mongodb:27017/?authSource=admin"}
      MARIADB_USER: ${MARIADB_USER:-"root"}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-"password"}
      MARIADB_HOST: ${MARIADB_HOST:-"mariadb"}
      MARIADB_PORT: ${MARIADB_PORT:-3306}

networks:
  dataviz:
    driver: bridge
